styla_cms_integration_administration:
    resource: '../../Controller/*Controller.php'
    type: annotation

styla_cms_integration_storefront:
    resource: '../../Controller/Storefront/*Controller.php'
    type: annotation
